### ISSUE TITLE
Remove comments in stopwatch.js

### ISSUE THREAD

**Issue by katbow** [olot/stopwatchtm#16]
Code is clean enough to be self explanatory - do you need the comments?
There's also a couple of console.log statements which could be removed.

**Comment by tas12** [comment]
Removed comments and console.log. See commit [beb93e8](https://github.com/olot/stopwatchtm/commit/beb93e8644faf72f2c355a694a7f596e40ce4ee1)

**Comment by katbow** [comment]
Looks great, thanks @tas12
